# Generated by Django 5.2.1 on 2025-06-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='recipe_name',
        ),
    ]
