# Generated by Django 5.2.1 on 2025-06-20 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_title_recipe_recipe_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='recipe_description',
        ),
    ]
