# Generated by Django 5.2.1 on 2025-07-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_reportcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportcard',
            options={'ordering': ['student__student_name']},
        ),
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('rank', 'date_of_generating')},
        ),
    ]
