# Generated by Django 5.2.1 on 2025-07-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_reportcard_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportCard',
            new_name='StudentReportCard',
        ),
    ]
