# Generated by Django 5.2.1 on 2025-07-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_rename_reportcard_studentreportcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreportcard',
            name='date_of_generating',
            field=models.DateField(auto_now_add=True),
        ),
    ]
