# Generated by Django 5.2.1 on 2025-07-03 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_alter_studentreportcard_date_of_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectmark',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='recipe.studentreportcard'),
        ),
    ]
