# Generated by Django 5.2.1 on 2025-07-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0014_studentreportcard_result'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreportcard',
            unique_together={('rank', 'total_marks')},
        ),
    ]
