# Generated by Django 5.2.1 on 2025-07-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0015_alter_studentreportcard_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreportcard',
            unique_together={('total_marks', 'student')},
        ),
    ]
