# Generated by Django 5.2.1 on 2025-07-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_alter_studentreportcard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreportcard',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
