# Generated by Django 5.2.1 on 2025-07-04 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_alter_studentreportcard_rank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentreportcard',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='studentreportcard',
            name='rank',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentreportcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_card', to='recipe.student'),
        ),
    ]
