# Generated by Django 5.2.1 on 2025-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_alter_studentreportcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreportcard',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
