# Generated by Django 5.2.1 on 2025-06-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
